import {
  CirclePlus,
  House,
  MessageCircle,
  Search,
  UserRound,
} from "lucide-react";

export const MobileNavIcon = [
  {
    id: 1,
    icon: House,
    label: "Home",
    href: "/",
  },
  {
    id: 2,
    icon: Search,
    label: "Search",
    href: "/search",
  },
  {
    id: 3,
    icon: CirclePlus,
    label: "add",
    href: "/add",
  },
  {
    id: 4,
    icon: MessageCircle,
    label: "Comment",
    href: "/comments",
  },
  {
    id: 5,
    icon: UserRound,
    label: "Profile",
    href: "/profile",
  },
];

//TODO: TO BE DELETED WHEN BACKEND IS IMPLEMENTED
export const ExploreMarketData = [
  {
    id: 1,
    title: "Taste of Naija",
    description: "Specializing in authentic Nigerian Cuisine.",
    address: "2 Ode street, Garki, Abuja.",
    image: "/product1.jpg",
    hour: "Monday to Saturday: 9:00AM - 9:00PM",
    email: "info@tasteofnaija.ng",
    phone: "0800 000 000",
    website: "tasteofnaija.ng",
    category: "Food",
    reviews: 4,
    likes: 500,
    dislikes: 200,
    price: 100,
    availability: true,
  },
  {
    id: 2,
    title: "Nigerian Fashion Week",
    description:
      "Nigerian Fashion Week is a popular event where fashion designers and stylists showcase their work.",
    address: "30 Adeola street, Garki, Abuja.",
    image: "/product2.jpg",
    hour: "Monday to Saturday: 10:00AM - 10:00PM",
    email: "info@nigerianfashionweek.ng",
    phone: "0800 000 001",
    website: "nigerianfashionweek.ng",
    category: "Fashion",
    reviews: 4.8,
    likes: 600,
    dislikes: 150,
    price: 7800,
    availability: true,
  },
  {
    id: 3,
    title: "Nigerian Farmers Market",
    description:
      "The Nigerian Farmers Market is a popular event where Nigerians come together to buy fresh produce.",
    address: "15 Ode street, Garki, Abuja.",
    image: "/product3.jpg",
    hour: "Monday to Saturday: 9:00AM - 11:00PM",
    email: "info@nigerianfarmersmarket.ng",
    phone: "0800 000 002",
    website: "nigerianfarmersmarket.ng",
    category: "Market",
    reviews: 4.6,
    likes: 450,
    dislikes: 100,
    price: 5000,
    availability: true,
  },
  {
    id: 4,
    title: "Nigerian Art Gallery",
    description:
      "The Art Gallery is a popular event where Nigerians come together to buy fresh produce.",
    address: "20 Adeola street, Garki, Abuja.",
    image: "/product4.jpg",
    hour: "Monday to Saturday: 10:00AM - 11:00PM",
    email: "info@nigerianartgallery.ng",
    phone: "0800 000 003",
    website: "nigerianartgallery.ng",
    category: "Art",
    reviews: 4.7,
    likes: 550,
    dislikes: 120,
    price: 3500,
    availability: true,
  },
  {
    id: 5,
    title: "Nigerian Musical Festival",
    description:
      "The Nigerian Musical Festival is a popular event where Nigerians come together to buy fresh produce.",
    address: "25 Adeola street, Garki, Abuja.",
    image: "/product5.jpg",
    hour: "Monday to Saturday: 9:00AM - 11:00PM",
    email: "info@nigerianmusicalfestival.ng",
    phone: "0800 000 004",
    website: "nigerianmusicalfestival.ng",
    category: "Music",
    reviews: 4.9,
    likes: 600,
    dislikes: 80,
    price: 4000,
    availability: false,
  },
];

export const profileData = {
  id: 1,
  name: "Elegance by enoila",
  email: "johndoe@example.com",
  phone: "0800 000 000",
  address: "25 Adeola street, Garki, Abuja",
  image: "/profile.jpg",
  about:
    "Elegance by Eniola specializes in custom-made outfits, ready-to-wear collections, and bridal couture for clients who desire unique, elegant styles.",
  bio: "I am a software engineer who loves exploring new technologies.",
  website: "johndoe.com",
  posts: 100,
  comments: 200,
  likes: 300,
  dislikes: 150,
  totalEarnings: 2000,
  createdAt: "2021-01-01",
  updatedAt: "2021-05-31",
  followers: 500,
  following: 100,
  openingHour: "Monday to Friday: 9:00AM - 7:00 PM",
  products: [
    {
      id: 1,
      title: "Custom T-Shirt",
      description: "A custom-made T-Shirt for a client.",
      price: 1500,
      image: "/product1.jpg",
      availability: true,
      category: "Fashion",
      reviews: 3.5,
      likes: 350,
    },
    {
      id: 2,
      title: "Custom Jacket",
      description: "A custom-made jacket for a client.",
      price: 2000,
      image: "/product2.jpg",
      availability: true,
      category: "Fashion",
      reviews: 4.7,
      likes: 400,
    },
    {
      id: 3,
      title: "Custom Dress",
      description: "A custom-made dress for a client.",
      price: 3000,
      image: "/product3.jpg",
      availability: true,
      category: "Fashion",
      reviews: 4.0,
      likes: 250,
    },
    {
      id: 4,
      title: "Custom Shoes",
      description: "A custom-made shoes for a client.",
      price: 1000,
      image: "/product4.jpg",
      availability: true,
      category: "Fashion",
      reviews: 4.8,
      likes: 300,
    },
  ],
};

export const ReviewsData = [
  {
    id: 1,
    user: "John Doe",
    rating: 4,
    content: "This product is amazing!",
    date: "2022-01-01",
    image: "/assets/Ellipse 22.svg",
  },
  {
    id: 2,
    user: "Jane Smith",
    rating: 5,
    content: "I love this product!",
    date: "2022-02-01",
    image: "/assets/Ellipse 23.svg",
  },
  {
    id: 3,
    user: "Jane Doe",
    rating: 3,
    content:
      "Elegance by Eniola has a good customer care service. They answered me speedily and made sure I was satisfied with their delivery. Lorem ispum de amet cot. ",
    date: "2022-03-01",
    image: "/assets/Ellipse 21.svg",
  },
];

export const bookMarkData = [
  {
    id: 1,
    title: "Bella Boutique",
    content: "your go-to store for female wears",
    img: "/assets/bookMark19.svg",
  },
  {
    id: 2,
    title: "Piim fashion",
    content: "the world's most expensive brand",
    img: "/assets/bookMark18.svg",
  },
  {
    id: 3,
    title: "Patagonia",
    content: "the world's best footwear brand",
    img: "/assets/bookMark17.svg",
  },
  {
    id: 4,
    title: "Zara",
    content: "the world's most popular women's fashion brand",
    img: "/assets/bookMark16.svg",
  },
];

export const messageData = [
  {
    id: 1,
    message: "Hello, this is the first message.",
    sender: "John Joe",
    img: "/assets/msg16.svg",
  },
  {
    id: 2,
    message: "This is the second message.",
    sender: "Jane Doe",
    img: "/assets/msg17.svg",
  },
  {
    id: 3,
    message: "Hello, this is the third message.",
    sender: "John Joe",
    img: "/assets/msg18.svg",
  },
];

export const photoDatas = [
  {
    id: 1,
    src: "/assets/Rectangle 265.svg",
    title: "Purple throw Pillow",
    price: 5000,
  },
  {
    id: 2,
    src: "/assets/Rectangle 264.svg",
    title: "Creamy red throw Pillow",
    price: 4500,
  },
  {
    id: 3,
    src: "/assets/Rectangle 263.svg",
    title: "Dark blue throw Pillow",
    price: 4000,
  },
  {
    id: 4,
    src: "/assets/Rectangle 262.svg",
    title: "Light blue throw Pillow",
    price: 3500,
  },
  {
    id: 5,
    src: "/assets/Rectangle 261.svg",
    title: "Light gray throw Pillow",
    price: 3000,
  },
];

export const productInHomePage = [
  {
    id: 1,
    businessName: "Bella boutique",
    businessDescription:
      "Bella focusing the project with the following business description",
    businessImage: "/assets/bookMark17.svg",
    createdAt: "2022-01-01T00:00:00.000Z",
    products: [
      {
        id: 1,
        name: "Supag Bathing Suit",
        price: 15000,
        image: "/assets/Rectangle 266.svg",
        description: "A super cute and stylish bathing suit for women.",
        availability: true,
        category: "Fashion",
      },
      {
        id: 2,
        name: "Supag Dress",
        price: 12000,
        image: "/assets/Rectangle 267.svg",
        description: "A super cute and stylish dress for women.",
        availability: true,
        category: "Fashion",
      },
      {
        id: 3,
        name: "Supag Shoes",
        price: 10000,
        image: "/assets/Rectangle 268.svg",
        description: "A super cute and stylish shoes for women.",
        availability: true,
        category: "Fashion",
      },
      {
        id: 4,
        name: "Supag Jacket",
        price: 8000,
        image: "/assets/Rectangle 269.svg",
        description: "A super cute and stylish jacket for women.",
        availability: true,
        category: "Fashion",
      },
    ],
  },
  {
    id: 2,
    businessName: "Piim fashion",
    businessDescription:
      "Piim focusing the project with the following business description",
    businessImage: "/assets/bookMark18.svg",
    createdAt: "2022-02-01T00:00:00.000Z",
    products: [
      {
        id: 1,
        name: "Piim Bathing Suit",
        price: 15000,
        image: "/assets/Rectangle 261.svg",
        description: "A stylish and cute bathing suit for women.",
        availability: true,
        category: "Fashion",
      },
      {
        id: 2,
        name: "Piim Dress",
        price: 12000,
        image: "/assets/Rectangle 262.svg",
        description: "A stylish and cute dress for women.",
        availability: true,
        category: "Fashion",
      },
      {
        id: 3,
        name: "Piim Shoes",
        price: 10000,
        image: "/assets/Rectangle 263.svg",
        description: "A stylish and cute shoes for women.",
        availability: true,
        category: "Fashion",
      },
      {
        id: 4,
        name: "Piim Jacket",
        price: 8000,
        image: "/assets/Rectangle 264.svg",
        description: "A stylish and cute jacket for women.",
        availability: true,
        category: "Fashion",
      },
    ],
  },
];
